language: java
jdk:
    - openjdk8

# master branch에 push 될 때만 수행
branches:
    only:
        - master
# Travis CI 서버의 홈
# 의존성은 다음 배포 때부터 다시 받지 않도록 설정해놓는 것.
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

# master branch 에 푸시되었을 때 수행하는 명령어임
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
    email:
        recipients:
            - annmyongjin7782@gmail.com